"""empty message

Revision ID: 90a035af6d9e
Revises: 45fef6624474
Create Date: 2017-04-25 07:06:23.066320

"""

# revision identifiers, used by Alembic.
revision = '90a035af6d9e'
down_revision = '45fef6624474'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_item', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('wishlist_item', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_item', 'url')
    op.drop_column('wishlist_item', 'description')
    # ### end Alembic commands ###
